# Generated by Django 3.1.5 on 2021-02-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_auto_20210210_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='Status',
            field=models.CharField(default='Active', max_length=10),
        ),
    ]
