# Generated by Django 3.1.5 on 2021-02-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_hospital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='Owner_Password',
            field=models.CharField(default='Medyadmin', max_length=20),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Owner_Username',
            field=models.CharField(default='Medfly@admin', max_length=20),
        ),
    ]
