# Generated by Django 3.1.5 on 2021-02-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0004_auto_20210210_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hosp_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('Department_Name', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Deparment',
        ),
    ]
