# Generated by Django 3.1.5 on 2021-02-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hosp_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('Department_Name', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Menu_Name', models.CharField(max_length=100)),
                ('Menu_Path', models.CharField(max_length=100)),
                ('Menu_Icon', models.CharField(max_length=100)),
                ('Menu_Status', models.CharField(default='Active', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Procedures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_ID', models.PositiveIntegerField()),
                ('Department_Name', models.CharField(blank=True, max_length=120, null=True)),
                ('Procedure_Name', models.CharField(blank=True, max_length=120, null=True)),
                ('Procedure_Status', models.CharField(default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role_ID', models.PositiveIntegerField()),
                ('Role_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Department_ID', models.PositiveIntegerField(default=0)),
                ('Department_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Permissions', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_ID', models.PositiveIntegerField()),
                ('Department_Name', models.CharField(blank=True, max_length=120, null=True)),
                ('Procedure_Name', models.CharField(blank=True, max_length=120, null=True)),
                ('Template_Name', models.CharField(blank=True, max_length=120, null=True)),
                ('Template_Status', models.CharField(default='Create', max_length=20)),
            ],
        ),
    ]
