# Generated by Django 3.1.5 on 2021-02-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hspId', models.CharField(blank=True, max_length=50, null=True)),
                ('menu_name', models.CharField(blank=True, max_length=50, null=True)),
                ('menu_state', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.PositiveIntegerField(blank=True, null=True)),
                ('permation_menu', models.CharField(blank=True, max_length=100, null=True)),
                ('permations', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
