# Generated by Django 3.1.5 on 2021-02-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0002_menu_userpermations'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_rout',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
