# Generated by Django 3.1.5 on 2021-02-27 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0003_auto_20210226_1218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPermations',
            new_name='UserPermai',
        ),
    ]
