# Generated by Django 3.1.5 on 2021-02-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0004_auto_20210227_1736'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='UserPermai',
        ),
    ]
